FROM public.ecr.aws/lambda/nodejs:20
# FROM node:20

WORKDIR ${LAMBDA_TASK_ROOT}
# WORKDIR /var/task
# copy
COPY package*.json ./
RUN npm install

COPY . .

# Lambda func
CMD [ "index.handler" ]

# Set the entrypoint to bash
# ENTRYPOINT ["/bin/bash"]